version: "2"

services:

  db:
    container_name: postgresql
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
    volumes:
      - /var/run/postgresql:/var/run/postgresql

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    environment:
      - STORAGE_TYPE=mem
      - JAVA_OPTS=-Dlogging.level.zipkin=DEBUG -Dlogging.level.zipkin2=DEBUG
    ports:
      - 9411:9411

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./config:/prometheus
    command:
      - '--config.file=prometheus.yml'
    ports:
      - 9090:9090

  users:
    build:
      context: .
      dockerfile: users/Dockerfile
    restart: always
    environment:
      - PG_HOST=db
      - PG_PORT=5432
      - PG_PASS=
      - PG_USER=postgres
      - PG_DB=postgres
    volumes:
    - .:/go/src/github.com/sohaibfarooqi/fragbook
    container_name: users
    ports:
    - 8081:8081
