scrape_configs:
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
    - targets: ['prometheus:9090']

  - job_name: 'api-server'
    scrape_interval: 5s # for demo purpose
    static_configs:
    - targets: ['users:8080']
